### ISSUE TITLE
CI Solution

### ISSUE THREAD

**Issue by NogsMPLS** [DigitalRiver/react-atlas#14]
Need to look into a good Continuous Integration solution. Possibly Travis CI?

**Comment by ericsewalson** [comment]
netlify is another CI solution to maybe research.

**Comment by hbowden** [comment]
We should run the tools discussed in the issues below on each pull request via our CI environment.

vuln checker: https://github.com/DigitalRiver/react-atlas/issues/264
license checker: https://github.com/DigitalRiver/react-atlas/issues/263
flow type checking: https://github.com/DigitalRiver/react-atlas/issues/261
prop comment checking: https://github.com/DigitalRiver/react-atlas/issues/258
eslint
prettier
accessibility checker

**Comment by hbowden** [comment]
Fixed by https://github.com/DigitalRiver/react-atlas/pull/367
