### ISSUE TITLE
Fix proptypes warnings in Switch component.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#187]
Various props need to be added to Switch's proptypes object to fix warnings.

![switch proptypes](https://user-images.githubusercontent.com/12447474/28027013-64904f9c-655d-11e7-82fb-7440cd2f8de1.png)

**Comment by pbalzano91** [comment]
https://github.com/DigitalRiver/react-atlas/pull/235

**Comment by hbowden** [comment]
Pato fixed in the pull above.
