### ISSUE TITLE
Codegen: Codegen adds a undefined prop to the Input component.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#188]
Codegen outputs an undefined proptype which throws a warning.

![input-undefined](https://user-images.githubusercontent.com/12447474/28038810-b5e31474-6585-11e7-8988-d1633ace8134.png)

here an example of the code codegen outputs:
![input-undefined-example](https://user-images.githubusercontent.com/12447474/28039034-894e3122-6586-11e7-90fe-e2ee6e1d186d.png)

**Comment by Raymans** [comment]
It's happened if props is defined in defaultProps but not existed in propTypes

**Comment by hbowden** [comment]
Sweet good find.
