### ISSUE TITLE
Redefine some linting rules

### ISSUE THREAD

**Issue by pbalzano91** [DigitalRiver/react-atlas#191]
**Main one**
"Component should be written as pure function" (not important anymore as we're extending PureComponent)

**Others**
"Definition for rule react/require-extension was not found" (I think it's deprecated - should check)

**Comment by pbalzano91** [comment]
https://github.com/DigitalRiver/react-atlas/pull/236

**Comment by hbowden** [comment]
Fixed in above pull request.
