### ISSUE TITLE
Codegen: Production builds of Atlas are broken.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#197]
When building Atlas with `NODE_ENV="production"` Atlas components can't be imported into other applications.  Imports probably need a change so components can be imported correctly. Does not happen with developmemt builds.

![prod bug](https://user-images.githubusercontent.com/12447474/28387238-ea0b297a-6c93-11e7-9ab6-1194cb52755a.png)

**Comment by pbalzano91** [comment]
https://github.com/DigitalRiver/react-atlas/pull/233

**Comment by hbowden** [comment]
Fixed by Pato in above pull.
