### ISSUE TITLE
ClassNames, classNames, className, this.props.className

### ISSUE THREAD

**Issue by NogsMPLS** [DigitalRiver/react-atlas#23]
After going through quite a few components I'm noticing 1 particular annoyance. That is, exactly how should we handle 'className' vars?

Let's take a common component that uses the [classnames project](https://github.com/JedWatson/classnames)

``` javascript
import ClassNames from 'classnames/bind';
import style from './styles.css';

const someComponent = ({className, children, ...props}) => {
    const cx = ClassNames.bind(style);
    const classNames = cx({
        base: true,
        className
    })

    return (
        <div className={classNames}>
             {children}
        </div>
    )
}
```

This can get real annoying. Luckily WebStorm has extremely good syntax highlighting which helps alleviate this issue a bit, but not everyone has webstorm as an IDE.

What naming policies should we come up with to fix this?

**Comment by hbowden** [comment]
Will need to investigate react themable first before deciding on classNames().
