### ISSUE TITLE
Dropdown's onClick prop fires multiple times

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#232]
onClick fires the callback multiple times when the onClick event fires;

1) once before the actual click
2) two times after the click change

See picture for changing dropdown value from Afghanistan => Albania:

![image](https://user-images.githubusercontent.com/1256043/29137704-d87e9970-7d06-11e7-857e-5ace15fde500.png)

**Comment by hbowden** [comment]
Fixed by #291
