### ISSUE TITLE
Input - bad behavior with maxLength set

### ISSUE THREAD

**Issue by aaciar** [DigitalRiver/react-atlas#241]
- Scenario: Input configured with maxLength. 
- Observation: if an string longer than maxLength is entered, the input does not handle it properly, it save teh string (overpassing the maxLenght) inside the component  without any error.
In this situation, the string is truncated inside function _validate(inputValue), but it is (wrongly) overwritten after that.

**Comment by hbowden** [comment]
Fix is here: https://github.com/DigitalRiver/react-atlas/pull/288
