### ISSUE TITLE
Dropdown component doesn't close on blur sometimes

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#248]
Hard to replicate.  I was lucky enough to capture it this time.

![image](https://user-images.githubusercontent.com/1256043/29533744-ec13d948-8678-11e7-8860-d6a237559163.png)

**Comment by hbowden** [comment]
I haven't been able to reproduce this so far.

**Comment by hbowden** [comment]
Fixed.
