### ISSUE TITLE
Radio's documentation should just show Radio not RadioGroup.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#260]

**Comment by javipisobeto** [comment]
@hbowden you mean that  `<RadioGroup name="test">` tag should be replaced with `<Radio>` ?

**Comment by stuller** [comment]
Right now RadioGroup is required for Radio to function properly.  Documentation provides contextual use case.  If use case is presented in the future, we can create another issue to remove the dependency on RadioGroup.
