### ISSUE TITLE
CORS Vulnerability in dependency 

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#266]
```
[748/873] sockjs 0.3.18  [VULNERABLE]
3 known vulnerabilities, 1 affecting installed version

CORS vulnerability
The package automatically sets the `Access-Control-Allow-Origin` header to whatever the requesting doma
in is, if any sockjs path is referenced from another domain. This enables a possible CORS attack.

The fix is a change that optionally disables the CORS headers.

Affected versions: <=0.3.18
References:
  * https://github.com/sockjs/sockjs-node/issues/217
  * https://github.com/sockjs/sockjs-node/pull/218
------------------------------------------------------------```

**Comment by Magneticmagnum** [comment]
There is currently a PR for this waiting in sockjs github: https://github.com/sockjs/sockjs-node/pull/218#pullrequestreview-17716766

However, doesn't seem like they are going to fix it.  We can fork and use it as it is MIT license.

**Comment by hbowden** [comment]
Yea we can fork until/if they merge that PR, we can't create a release with a known vulnerability.

**Comment by NogsMPLS** [comment]
FYI, that PR has been merged. update dependencies and run the vulnerability test again to see if this can be closed.

**Comment by hbowden** [comment]
K sweet, I'll check.

**Comment by hbowden** [comment]
Still getting the error, we probably need to update one of our deps.

**Comment by Magneticmagnum** [comment]
Check again?  I'm no longer seeing the issue when I used Synk.io to check the repo's dependencies

**Comment by stuller** [comment]
Can this be closed?

**Comment by Magneticmagnum** [comment]
No longer seeing the vulnerability.  Closing issue.
