### ISSUE TITLE
Dropdown CSS spacing bug on mobile chrome.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#268]
Should be no space between dropdown button and dropdown menu.

![screenshot_20170827-104952](https://user-images.githubusercontent.com/12447474/29778997-ce55dad8-8bd6-11e7-9809-705f7d0cca5b.jpg)

**Comment by hbowden** [comment]
Reported by @NogsMPLS

**Comment by javipisobeto** [comment]
does this still happens @hbowde ? i checked recently on Chrome 62.0.3202.84 Android 6.0 and dropdown behaves the same way that on website.

**Comment by hbowden** [comment]
@javipisobeto It works on your phone?

**Comment by javipisobeto** [comment]
Yeah @hbowden, i just tested it and it leaves the same amount of space than on the website.  Attaching screenshot: 

![screenshot_20171115-154002](https://user-images.githubusercontent.com/5483911/32853869-73022fb4-ca1b-11e7-8397-26afc76d5768.png)

**Comment by hbowden** [comment]
@javipisobeto You can close it, if it's working for you.

**Comment by javipisobeto** [comment]
Closing according to evidence attached.
