### ISSUE TITLE
Radio CSS bug on chrome mobile.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#269]
HTML5 radio is peeking out from under custom radio.

![screenshot_20170827-105309](https://user-images.githubusercontent.com/12447474/29779077-13bb6732-8bd7-11e7-8e38-be9320826d5d.jpg)

**Comment by hbowden** [comment]
Reported by @NogsMPLS

**Comment by ericsewalson** [comment]
resolved by PR 350
