### ISSUE TITLE
Separate Styles From Base Components

### ISSUE THREAD

**Issue by NogsMPLS** [DigitalRiver/react-atlas#27]
After reading: https://github.com/nikgraf/future-react-ui and https://github.com/nikgraf/future-react-ui/issues/1 I am starting to think that we should look into separating out the close coupling of the CSS and the React Components in this library.

Doing so will allow us to have some more flexibility in regards to styling and functionality. We can make sure that the core components themselves are application-agnostic in regards to style. We can make a 'react-atlas-dr' repo, or perhaps have that inside the project as go-to default 'prototype' styled components for people to use out-of-the-box. We can also make a bootstrapped styled repo that uses bootstrap styles, but the react-atlas-core components.

**Comment by NogsMPLS** [comment]
with https://github.com/DigitalRiver/react-atlas/commit/45c5d8ca4be8717865aa1dc99035b1d8956493a7 we have the first steps of this implemented.

I think if we can get local modules working as described here: https://medium.com/@arnaudrinquin/build-modular-application-with-npm-local-modules-dfc5ff047bcc#.1p1zbnbfl

If we can get that working on the atlas-core directory and the drStyled directory, we will have smooth separation of the two.

I think eventually our npm publish commands will publish both a atlas-core and a atlas-styled or atlas-themed repos.

This will allow for people to use atlas-themed for quick prototyping, and atlas-core for true style customization if they want.

**Comment by NogsMPLS** [comment]
Decent commit to reference for this work: https://github.com/DigitalRiver/react-atlas/commit/5d961f34c7b36105128e4b5dd07ac64ad725eb24

**Comment by hbowden** [comment]
Styles are now fully separated form component logic.
