### ISSUE TITLE
Determine Test Framework/Suite

### ISSUE THREAD

**Issue by NogsMPLS** [DigitalRiver/react-atlas#29]
Original repo used karma and mocha. that's a decent combo, but we should consciously chose what we want to use.

Some older standards that work are karma combinations like:
Karma + Mocha + Chai + Sinon
Karma + Jasmine

However, we should also look into some of the newer testing utilies:
https://github.com/airbnb/enzyme
https://github.com/facebook/jest
https://github.com/substack/tape

Headless stuff to look into, depending on how abstract we wanna go:
https://github.com/hughsk/smokestack
https://github.com/segmentio/nightmare
https://github.com/johntitus/node-horseman
https://github.com/SeleniumHQ/selenium
https://github.com/ariya/phantomjs

**Comment by hbowden** [comment]
@NogsMPLS Was there anything wrong with karma and mocha/ why was karma and mocha not brought into this repo?

**Comment by NogsMPLS** [comment]
there is no testing framework in it really currently. this issue/ticket is just for looking into. its up to you guys what to decide on.

**Comment by hbowden** [comment]
This issue could be closed now that cfa83f34254c271158f9d1bb76067f568fda46b2 has been merged.
