### ISSUE TITLE
Dropdown uses wrong error message in some cases.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#303]
Dropdown fires required error message when no name is set and required prop is set when inside a form component submitting. Should not fire a required error message, but should maybe throw an exception or a different error message.

```
    <Form onSubmit={function(event, data) {console.log("event: ", event); console.log("data: ", data);}}>
        <Dropdown required customLabel="Choose">
          <span value="bird">Bird</span>
          <span value="cow" selected>Cow</span>
          <span value="cbpcdmh">Cow Bird Pick Cat Dog Monkey Human</span>
          <span value="monkey">Monkey</span>
          <span value="eee">eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee</span>
        </Dropdown>
	<Button type="submit">Submit</Button>
    </Form>
```

**Comment by stuller** [comment]
@hbowden I can't reproduce this one - what actions does the user need to take to reproduce?  I tried hitting submit without making a selection, and also tried making a selection and then hitting submit, but couldn't reproduce.

**Comment by hbowden** [comment]
Affected the old Dropdown.
