### ISSUE TITLE
Dropdown should have it's name passed with its event

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#330]
onChange should return it's event that also passes long its name.

This is to ensure it matches the other events handled by TextField, TextArea, and Input.

ie: [event.target.name] returns it's prop name

**Comment by hbowden** [comment]
@Magneticmagnum So you want the event object to have `event.name` be a property?

**Comment by stuller** [comment]
Need more clarification - which other components return the name prop in the onChange response?
