### ISSUE TITLE
TextField / TextArea custom validation doesn't show it's custom error message

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#332]
![image](https://user-images.githubusercontent.com/1256043/31344900-b0680b94-acd9-11e7-847f-cc675f9ffea7.png)

**Comment by Darper** [comment]
Introduced with pull #234 addition of componentWillReceiveProps.

**Comment by Darper** [comment]
Half fixed by #447 but still broken when using inside Form component.

**Comment by hbowden** [comment]
Fixed by pull: https://github.com/DigitalRiver/react-atlas/pull/515
