### ISSUE TITLE
Tooltip pushes the entire component to the page if it's passed into as the tip

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#335]
Initial state:
![image](https://user-images.githubusercontent.com/1256043/31345189-90c34618-acda-11e7-8bad-9efc9a6f2141.png)

After Hover, its not fully displaying the component:
![image](https://user-images.githubusercontent.com/1256043/31345224-ab3c6308-acda-11e7-8430-d2d0ef0ae6d0.png)

After inital hover, the entire tip component is rendered on page permanently:
![image](https://user-images.githubusercontent.com/1256043/31345251-bb655afa-acda-11e7-8272-dd666d9658c4.png)

**Comment by ericsewalson** [comment]
Added Active class and set tooltip class to always be used to fix this defect.
