### ISSUE TITLE
Update lerna documentation

### ISSUE THREAD

**Issue by ericsewalson** [DigitalRiver/react-atlas#35]

**Comment by NogsMPLS** [comment]
what exactly do we mean by update lerna documentation?

I'm assuming it's referring to like, make some documentation or steps referring to how to use the monorepo structure?

**Comment by Darper** [comment]
Eric can't remember what this is

**Comment by hbowden** [comment]
All this is auto magically taken cared of, so no need for lerna specific documentation.
