### ISSUE TITLE
Initial module install issues

### ISSUE THREAD

**Issue by ericsewalson** [DigitalRiver/react-atlas#36]
There is something going on with the package configuration or something causing an issue with using npm install to load packages.

**Comment by Magneticmagnum** [comment]
What's the error? Can you post a the log

**Comment by NogsMPLS** [comment]
I'm hoping this is fixed when #39 gets merged in. 🙏

**Comment by Magneticmagnum** [comment]
Closed issue until further information is provided.  Following the readme now should work.
