### ISSUE TITLE
Modal throws an error: className not defined

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#376]
Replication: Try to open Modal component in current styleguidist

![image](https://user-images.githubusercontent.com/1256043/31717984-c7a6a74c-b3d3-11e7-9f60-a217f9220d30.png)

**Comment by Magneticmagnum** [comment]
I believe it's this commit: 

https://github.com/DigitalRiver/react-atlas/pull/371/files

**Comment by hbowden** [comment]
Fixed by: https://github.com/DigitalRiver/react-atlas/pull/379
