### ISSUE TITLE
Table throws an error when searching in the search bar.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#386]
![table-search-bug](https://user-images.githubusercontent.com/12447474/31780846-8756776e-b4bc-11e7-9e97-1f0e2f219f41.png)

**Comment by Magneticmagnum** [comment]
How do you replicate this?

**Comment by hbowden** [comment]
```<Table data={[{id: 0, name: "Bear", price: "$100"}, {id: 1, name: "Corn", price: "$2"}, {id: 2, name: "Shark Banana", price: "$125"}]} search={true}>
  <TableHeader dataField='id' searchable={true} isKey={true}>Product ID</TableHeader>
  <TableHeader dataField='name' searchable={true}>Product Name</TableHeader>
  <TableHeader dataField='price' searchable={true}>Product Price</TableHeader>
</Table>```

Then just type in the search bar and it should throw the error.

**Comment by Magneticmagnum** [comment]
I wonder if this is only in styleguidist.  Table search works in GC for me

**Comment by stuller** [comment]
I think this has been fixed sometime between when this issue was filed and now.  I can't reproduce.

**Comment by hbowden** [comment]
Yea your right @stuller

**Comment by Magneticmagnum** [comment]
Yeah sorry, I had it figured it out, and had it fixed sometime later forgetting to close this.  It was an issue with a mistyped code for that component that we imported over from react-bootstrap-table
