### ISSUE TITLE
1 pixel height difference

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#394]
See Image: 
![image](https://user-images.githubusercontent.com/1256043/31891616-91b599ca-b7cc-11e7-94c0-64368b647f75.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/1256043/31891646-a9e89e52-b7cc-11e7-9871-d23d5c42e536.png)

**Comment by hbowden** [comment]
Fixed by: https://github.com/DigitalRiver/react-atlas/pull/412
