### ISSUE TITLE
TextField Header background should be the same as the background-color it overlays

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#398]
Example:

![image](https://user-images.githubusercontent.com/1256043/31896808-46dd671c-b7da-11e7-8bc9-46b6ab037a4d.png)

The white area should be gray along with the rest.

**Comment by Magneticmagnum** [comment]
The classname that needs to be removed is `.ra_styles__bg-white`

**Comment by hbowden** [comment]
Fixed by #402
