### ISSUE TITLE
TextArea doesn't show error message when isValid={false}

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#407]

**Comment by Magneticmagnum** [comment]
However, when you make an call to it's onChange, it'll then show the error message

Styleguidist code:

```
<div> <TextArea header="hi" required inline small isValid={false}/> <Button /> </div>
```

Replication: It will be initially invalid.  type anything into the input field, and then delete all of it.  Once all the characters are deleted, error message shows.

**Comment by hbowden** [comment]
This is correct behavior. You have the required prop set so if you type and then remove text the required validation will fire.
