### ISSUE TITLE
Accordion: DatePicker not working inside

### ISSUE THREAD

**Issue by pbalzano91** [DigitalRiver/react-atlas#416]
This issue may be strictly related to #415, and it will probably be fixed when it is addressed.

![datepickerissue1](https://user-images.githubusercontent.com/6012986/32020202-c7967584-b9a5-11e7-9741-e79c35de2aed.PNG)

**Comment by Magneticmagnum** [comment]
This doesn't seem to be occuring in styleguidist latest mater.

**Comment by pbalzano91** [comment]
I'm using beta17, maybe is it outdated? Also, have you checked #415 ?

**Comment by ericsewalson** [comment]
I show this is working as expected in styleguidist.  Same for #415
