### ISSUE TITLE
Should not be setting initial state with prop value

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#465]
We should not be setting initial state with a prop value, as this can cause issues when modifying props. (Read https://stackoverflow.com/questions/41233458/react-child-component-not-updating-after-parent-state-change for an explanation). Go through the components below and either refactor to remove prop, remove state attribute, or use ComponentWillReceiveProps. 

- Accordion
- Checkbox
- Dropdown
- Input
- Switch
- TextArea
- TextField
- Tooltip

**Comment by Darper** [comment]
Here's an example of TextField's current state: https://codesandbox.io/s/n4opy48m1m

You'll see that the Paragraph component can update its value properly when parent state changes, but TextField value doesn't update.

**Comment by Raymans** [comment]
Trying to fix props in getinitialstate anti-pattern here,
making component as much as simple and should stay stateless as possible especially for props. 

Once we allow props in getInitialState may get out of sync later and cause maintenance trouble, also may overuse props into state and componentWillReceiveProps also be growing more complicated if go stay props in getInitialState.

Only leave props in getinitialstate when the props are permanent which never changed from parent like defaultText in Dropdown component.

**Comment by Darper** [comment]
Closing this issue. It has largely been fixed with the usage of componentWillReceiveProps, but we may come back to it soon due to the complexity of combining controlled and uncontrolled functionality. For more information, visit https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html.
