### ISSUE TITLE
Grid system component.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#487]
Create or import a react component to give users a bootstrap like grid system.

**Comment by hbowden** [comment]
I think we should import https://github.com/STRML/react-grid-layout and use that for our grid/layout component. It has a higher learning curve than things like bootstraps grid system but it has many more features.

**Comment by hbowden** [comment]
In progress: https://github.com/DigitalRiver/react-atlas/tree/layout

**Comment by Darper** [comment]
Closing. This is not something needed for React-Atlas. Applications should be able to choose their own grid systems to display Atlas components, and there are many options available via NPM with a variety of features.
