### ISSUE TITLE
Dropdown has position issues with list item container

### ISSUE THREAD

**Issue by ericsewalson** [DigitalRiver/react-atlas#494]
![image](https://user-images.githubusercontent.com/7217512/32737762-8d3059cc-c860-11e7-83da-35a4fef775ac.png)

The blue line just below the dropdown button.

**Comment by hbowden** [comment]
@ericsewalson Can you add example code.

**Comment by ericsewalson** [comment]
```
  <Dropdown onChange={(value) => { this._updateField("promoTypeId", index, value) }} defaultText="Select One ...">
            {this.props.promoTypes.map((type, index) => {
              return <span key={index} value={type.promoTypeId}>{type.promoTypeName}</span>;
            })}
          </Dropdown>
```

**Comment by javipisobeto** [comment]
@ericsewalson is the issue about the arrow button being outside the dropdown field? i tried reproducing the issue with no sucess, with the following code: 
```
let promoTypes = [
	{promoTypeId:"1",promoTypeName:"promoTypeName1"},{promoTypeId:"2",promoTypeName:"promoTypeName2"}
];
<Dropdown width="50px" onChange={(value) => { this._updateField("promoTypeId", index, value) }} defaultText="Select One...">
  {promoTypes.map((type, index) => {
    return <span key={index} value={type.promoTypeId}>{type.promoTypeName}</span>;
  })}
</Dropdown>
```
and got this result: 
![image](https://user-images.githubusercontent.com/5483911/34786112-e5162070-f611-11e7-9ae8-15df4e0f760b.png)

what could be missing to fully reproduce this?
