### ISSUE TITLE
Modal Title Bar Text Color Should be White

### ISSUE THREAD

**Issue by ericsewalson** [DigitalRiver/react-atlas#499]
![image](https://user-images.githubusercontent.com/7217512/32858857-6dae2d82-ca12-11e7-8d5e-3a5a4bfa6c8f.png)

From a consistency standpoint the header should have a while text color if the background is blue.

**Comment by javipisobeto** [comment]
My opinion is that text color should be white for every color case on modal, even with black.

**Comment by hbowden** [comment]
Fixed by https://github.com/DigitalRiver/react-atlas/pull/505
