### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#503]
Checked prop doesn't work

Styleguidist code:

```
<RadioGroup name="test">
	<Radio label="Option 1" value="first"/>
	<Radio label="Option 2" value="second" checked/>
</RadioGroup>
```

**Comment by hbowden** [comment]
Related to this issue #504

**Comment by stuller** [comment]
`<RadioGroup name="test" selectedValue="second">
	<Radio label="Option 1" value="first" defaultChecked/>
	<Radio label="Option 2" value="second"/>
</RadioGroup>`


defaultChecked on Radio overrides selectedValue on RadioGroup
