### ISSUE TITLE
Update Radio / RadioGroup Prop

### ISSUE THREAD

**Issue by Magneticmagnum** [DigitalRiver/react-atlas#504]
API for Radio / RadioGroup has changed;

Radio should no longer uses the following prop: `checked`

**Comment by stuller** [comment]
`<RadioGroup name="test" selectedValue="second">
	<Radio label="Option 1" value="first" defaultChecked/>
	<Radio label="Option 2" value="second"/>
</RadioGroup>`


defaultChecked on Radio overrides selectedValue on RadioGroup
