### ISSUE TITLE
Textfield: Custom Validation is broken

### ISSUE THREAD

**Issue by pbalzano91** [DigitalRiver/react-atlas#507]
Example code:
```
<TextField
	errorText="Only numbers are allowed."
	validator={ (value) => { return /^\d+$/.test(value) } }
	header="Only numbers allowed"/>
```
This does not work properly and it displays required error message instead of errorText provided.

**Comment by hbowden** [comment]
Duplicate of https://github.com/DigitalRiver/react-atlas/issues/332, closing this issue and will track in original issue.
