### ISSUE TITLE
Weird CSS issue with drop-down

### ISSUE THREAD

**Issue by prycec** [DigitalRiver/react-atlas#533]
![image](https://user-images.githubusercontent.com/2438374/33452634-7c194b28-d5d8-11e7-9e3d-31bdeb6dd2e5.png)

```html
            <Form>
                <Dropdown customLabel="HTTPS Method" width="5rem">
                    <span value="GET">GET</span>
                    <span value="POST">POST</span>
                    <span value="PUT">PUT</span>
                </Dropdown>
                <Button type="submit"/>
            </Form>
```

**Comment by prycec** [comment]
Also

When I use width="3rem" the drop down is not wide enough to display my values.

**Comment by hbowden** [comment]
Reproducible in docsite and about the width currently you have to set a width that works with your text.
