### ISSUE TITLE
Textfield and Textarea should allow for blank errorText.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#547]
Currently if you pass an empty string to Textfield or Textarea and the required message fires it uses the "this field is required"  message instead of a blank string. Below is an example with TextField.

```
<TextField required header="Email Address" requiredText="" errorText=" "/>
```

![2018-01-03 10_16_10-react atlas style guide](https://user-images.githubusercontent.com/12447474/34528656-29fc778c-f06f-11e7-8387-704176f1fd1b.png)

**Comment by javipisobeto** [comment]
currently in progress

**Comment by hbowden** [comment]
fixed by https://github.com/DigitalRiver/react-atlas/pull/552
