### ISSUE TITLE
Switch component style should match style guide

### ISSUE THREAD

**Issue by havebeeair** [DigitalRiver/react-atlas#576]
Swtich component should match digital river style guide https://www.digitalriver.staging.wpengine.com/styleguide/#forms-example

basically is going from this:
![current state](https://user-images.githubusercontent.com/5483911/35153693-5468baf0-fd06-11e7-9f3a-3d30008ec726.PNG)

to this:
![new style](https://user-images.githubusercontent.com/5483911/35153697-5d295d98-fd06-11e7-875e-fa925d24d575.PNG)

**Comment by stuller** [comment]
Derek has asked for updated style guide requirements that better address contrast for accessibility
