### ISSUE TITLE
Tabbing into TextField focuses on wrapper, not input.

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#620]
When using keyboard navigation to tab between inputs, tabbing onto a TextField will focus on the wrapper and provide styling, but not actually focus on the input to allow for user to enter text. In order to get into the input you need to hit tab twice, which is unexpected behavior for an online form.

**Comment by hbowden** [comment]
@Darper You fixed this right?

**Comment by stuller** [comment]
fixed
