### ISSUE TITLE
Input.js does not set required on the underlying <input /> element

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#637]
The input component should pass required to the `<input />` tag it renders. At the very least we need this for accessibility reasons: https://stackoverflow.com/questions/37974796/when-to-use-the-required-attribute-vs-the-aria-required-attribute-for-input-elem

**Comment by stuller** [comment]
Works for Input, TextField and TextArea.  Needs to be fixed for Checkbox.

**Comment by stuller** [comment]
fixed with PR #678
