### ISSUE TITLE
Tooltip is styling child elements with tooltip color

### ISSUE THREAD

**Issue by ericsewalson** [DigitalRiver/react-atlas#643]
Tooltip should not style the child elements with color and other default styling characteristics.

Styleguidist code to reproduce: `<Tooltip text="Icon child">Date Picker</Tooltip>`

![image](https://user-images.githubusercontent.com/7217512/36386524-a07bc49c-155b-11e8-9415-a5ada6226443.png)

**Comment by ericsewalson** [comment]
![image](https://user-images.githubusercontent.com/7217512/36386575-c65ae530-155b-11e8-83be-1b2d03a0f6f9.png)

**Comment by stuller** [comment]
is there an expectation that styles for children should be wiped out if the child itself has no style or className?  These two scenarios worked for me:

![image](https://user-images.githubusercontent.com/1141357/36551695-cc095110-17bd-11e8-8149-e4cf2e9d906e.png)

**Comment by stuller** [comment]
works for some components but not for plain text or for Text component.  

`<Tooltip text="Tooltip with child element"> <Text>foo</Text></Tooltip>`

![image](https://user-images.githubusercontent.com/1141357/37225501-6d5a3c34-239c-11e8-91d9-a5a4203a2f33.png)
