### ISSUE TITLE
Input component refactor / code review.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#674]
Here's the notes from our code review for the Input component.

1) Remove small, medium, and large props.

2) Use cols and row props for TextArea

3) Fix padding on label with required prop.

4) Only functional props in Input, no visual code in Input.

5) Remove all or as much CSS as possible from Input.

6) Move mask into it's own composable component.

7) Don't check or filter value prop, it's ok to accept undefined or null as a value.

8) No state change in validate. Do state changes if any inside onChange.

9) Move line 162 into onChange.

10) Remove whole if statement at line 166.

11) Turn function into arrow function on line 181.

12) Don't use .call(this) on line 192.

13) Remove isValid and errorText from Input's state.

14) Create prop called onValidate that takes a function that returns an isValid boolean and an string that determines the error.

15) Move uppercase functionality into TextField.

16) onChange should always be called even when inValid.

**Comment by stuller** [comment]
Input has been removed in 0.1.0
