### ISSUE TITLE
add autofocus prop to form input components

### ISSUE THREAD

**Issue by stuller** [DigitalRiver/react-atlas#703]
HTML inputs support an autofocus attribute that specifies that an input should have focus when a page loads.  

Would love to have this as a prop for form components, it's something we'd like to use on checkout.

**Comment by hbowden** [comment]
@stuller Should we have autofocus as a specific prop? or just pass down props on all components using like a prop spread or something.

**Comment by stuller** [comment]
passing down all props with a prop spread would be great.

**Comment by hbowden** [comment]
Fixed by https://github.com/DigitalRiver/react-atlas/pull/705
