### ISSUE TITLE
Avatar Review Notes

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#704]
- Remove line 7
- Make lines 16 & 17 multiline
- remove line 29 and make line 38 an arrow function
- remove semi-colon from line 36
- Remove child text check at line 55
- Change icon to allow strings and only strings
- Change image to only allow strings
- Remove image type checker & if else on line 71-73
- Replace kids with children in line 86
- icon PropTypes = string
- Add propspread so user can pass down custom props
- Add default-font to .avatar
- Update tests as necessary
- Update readme titles to reflect changes

**Comment by stuller** [comment]
Completed with PR #715
