### ISSUE TITLE
Link text should be more to the right.

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#721]
Link text on TextField should be right aligned with the textfield. There's a small amount of space between the link text and right side of the textfield.

![2018-04-03 10_59_51-verifysecretkeyformcontrollertest java c__dev_gc atom](https://user-images.githubusercontent.com/12447474/38260870-510744a0-372e-11e8-873f-80523500f6ac.png)

**Comment by stuller** [comment]
adding image from styleguide and example JSX here
![image](https://user-images.githubusercontent.com/1141357/38261169-1ccf59ce-372f-11e8-8ec8-4cd247be31d7.png)

`<TextField label="This is a TextField" linkText="foo" link linkRight/>`

**Comment by stuller** [comment]
closed with merge of PR #722
