### ISSUE TITLE
Button: Default Button has different colors in safari & chrome

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#852]

**Comment by floydchenchen** [comment]
##### default button in `chrome` (mac)
![image](https://user-images.githubusercontent.com/25163710/42167513-e85a1594-7dd3-11e8-8791-df4746c3d581.png)


##### default button in `safari` (mac)
![image](https://user-images.githubusercontent.com/25163710/42167571-0e5a775c-7dd4-11e8-86aa-4a8d785911b3.png)

**Comment by floydchenchen** [comment]
https://files.slack.com/files-pri/T10DLLRPC-FBKN6G3ND/image.png

**Comment by floydchenchen** [comment]
![image](https://user-images.githubusercontent.com/25163710/42392549-db0d1182-8118-11e8-8355-e79f4bef2d7a.png)
