### ISSUE TITLE
Datepicker: Next and Previous buttons are not consistent in chrome and safari

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#853]

**Comment by hbowden** [comment]
@Darper Can you post a screenshot when you get the chance?

**Comment by Darper** [comment]
@floydchenchen Can you post a screen shot from your mac?

**Comment by floydchenchen** [comment]
date picker on safari (mac):

![image](https://user-images.githubusercontent.com/25163710/42395230-c0c6f086-8122-11e8-8c9d-488dfd949b99.png)


date picker on chrome (mac):
![image](https://user-images.githubusercontent.com/25163710/42395261-dc11d1bc-8122-11e8-8e9c-115595d41dbe.png)

**Comment by stuller** [comment]
just guessing, because i don't have a mac on the network, but i think this just needs background-color set to transparent.  it looks weird with a background on both of them.
