### ISSUE TITLE
AccordionPanel: expanded prop only works with string value

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#898]
Even though the `expanded` prop in AccordionPanel is expecting a boolean, it only works if the value is set to a string of "true".

**Comment by stuller** [comment]
should it work with both?

**Comment by Darper** [comment]
It's coded to only work with booleans, but in reality it only works with strings. The intention was that boolean is required.

**Comment by stuller** [comment]
I think if we make it boolean, there will be errors when using regular divs, etc. for children.  html only has string attributes.  Do we want to restrict it to just AccordionPanel children? Either way, we should change the documentation for children prop, right now it says "Children should be either a string, an icon/glyphicon, or an image tag." which is misleading too.

**Comment by Darper** [comment]
Ah, sure. Then I suppose we should accept both.
