### ISSUE TITLE
font-awesome: Icons aren't working in Avater, BreadcrumbItem, or Icon components

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#899]
See docs site, icons are rendering as generic squares instead of actual icons.

**Comment by Darper** [comment]
Some icons also broken in Tabs examples.

**Comment by Darper** [comment]
Some icons seem to work while others don't, might be caused by version of font-awesome we're linking to. Some components (like Avatar) don't work with icons even when they work elsewhere.

**Comment by stuller** [comment]
readme files are updated for this one, but we'll need to publish docs before we close it.

**Comment by Darper** [comment]
Let's close it as quickly as possible so I can stop seeing my "Avater" typo.

**Comment by hbowden** [comment]
@stuller Good point I'll ask mag to publish a new doc site.
