### ISSUE TITLE
Remove caret in package.json from Jest, Enzyme, React, ReactDom

### ISSUE THREAD

**Issue by hbowden** [DigitalRiver/react-atlas#940]
This might be a over the top way of fixing the problem of unstable dependencies. This month we have had two Jest API breakages in minor version updates and one Enzyme API breakage. I'm tired of deps breaking our builds and the auto upgrading done by npm when a carret is in the semver. I would like to discus with the rest of the team what they think. But personally some of our downstream dev deps are far too unstable to be allowed to auto update minor versions. Here's the enzyme error for reference: https://github.com/airbnb/enzyme/issues/1747 and I'm too lazy to find the jest issues for the bugs that effected us.

**Comment by stuller** [comment]
yeah we should maybe discuss this in the next atlas code review.  I agree that the last few weeks have been painful

**Comment by hbowden** [comment]
Cool sounds good to me.

**Comment by stuller** [comment]
It was decided in team meeting to remove carets only from Jest, Enzyme, React, and ReactDom since those are the ones who have recently caused build issues.
