### ISSUE TITLE
Avatar Review Notes

### ISSUE THREAD

**Issue by Darper** [DigitalRiver/react-atlas#963]
JavaScript
- Line 14: Change defaultImage to fallbackImage
- Line 18: Replace `UNSAFE_componentWillReceiveProps` with `getDerivedStateFromProps`
- Line 40: Remove filteredProps and allow user to pass custom props if they want to.
- Lines 47-61: Convert lines to a getAvatar() function to reduce complexity of render function.
- Line 69: Add `style={style}`
- Line 70: Use new this.getAvatar() and only return children or prop data, not both.

Documentation
- Change "beats" to "takes precedence/priority"
- "Image beats icon" example fix icon from "fa" to "fab"
- List order of precedence in top descriptive paragraph
- Call out that icons will not fail down to Title, but instead not appear

**Comment by Darper** [comment]
Future enhancement
- Line 53: Possibly add onload event to remove flicker?

**Comment by stuller** [comment]
looks like these were all taken care of with PR #965
