### ISSUE TITLE
Form example causing js error - disabled prop example should use string, not boolean

### ISSUE THREAD

**Issue by stuller** [DigitalRiver/react-atlas#978]
On the doc site, there is a disabled field in the example for Form that is causing a JS prop type error.
The disabled field is passing disabled prop as a boolean, but it should be used as a string according to prop types.  

Derek will investigate whether we should change this prop to accept booleans as well, but in the meantime could you please update the example to use a string instead of boolean?

This is the error being displayed: 
![image](https://user-images.githubusercontent.com/1141357/48861611-a50a0580-ed89-11e8-9f20-fdb94f03b6e6.png)

**Comment by anneswanson** [comment]
Fixed with https://github.com/DigitalRiver/react-atlas/pull/985
