### ISSUE TITLE
Form hideErrors prop should not be passed down to html form element

### ISSUE THREAD

**Issue by stuller** [DigitalRiver/react-atlas#979]
The doc site has a js error caused by the hideErrors prop getting passed down to the html form element:
![image](https://user-images.githubusercontent.com/1141357/48862389-ddaade80-ed8b-11e8-988c-e72beb06548e.png)

Fix should just be adding hideErrors to the blacklist in this line like so:
`const othersFiltered = blacklist(others, "onSubmit", "hideErrors");`

That will prevent it from getting added to the <form> dom element, since it only gets othersFiltered.

You'll need to update snapshot test as well before putting in a PR.

**Comment by anneswanson** [comment]
Fixed with https://github.com/DigitalRiver/react-atlas/pull/986
